--CONECTANDO COM O BANCO DE DADOS
USE BDInGames;
GO

--LISTAR TODOS USUÁRIOS 	
SELECT * FROM Usuarios;
GO

--LISTAR TODOS OS ESTÚDIOS
SELECT * FROM Estudio;
GO

--LISTAR TODOS OS JOGOS
SELECT * FROM Jogo;
GO

--LISTAR TODOS OS TIPOS DE USUÁRIOS
SELECT * FROM TipoUsuario;
GO

--LISTAR TODOS OS JOGOS COM SEUS RESPECTIVOS ESTÚDIOS
select Jogo.NomeJogo, Estudio.NomeEstudio from Jogo
inner join Estudio on Estudio.IdEstudio = Jogo.IdEstudio;
GO

--LISTAR TODOS OS ESTÚDIOS COM SEUS RESPECTIVOS JOGOS
SELECT Estudio.NomeEstudio , Jogo.NomeJogo FROM Estudio
LEFT JOIN Jogo ON Jogo.IdEstudio = Estudio.IdEstudio;
GO

--LISTAR UM JOGO ESPECÍFICO PELO SEU ID
SELECT NomeJogo FROM Jogo
WHERE IdJogo = 2;
GO

--LISTAR UM USUÁRIO ATRAVÉZ DO SEU EMAIL E SENHA 
SELECT Email , Senha  FROM Usuarios 
WHERE Email LIKE '%cliente@cliente.com%' AND Senha LIKE '%cliente%';
GO


