--CRIAR O BANCO DE DADOS
CREATE DATABASE BDInGames;
GO

--CONECTANDO COM O BANCO DE DADOS
USE BDInGames;
GO

--CRIANDO AS TABELAS 
CREATE TABLE Estudio(
	IdEstudio INT PRIMARY KEY IDENTITY,
	NomeEstudio VARCHAR(255) NOT NULL UNIQUE
);
GO

CREATE TABLE Jogo(
	IdJogo INT PRIMARY KEY IDENTITY, 
	NomeJogo VARCHAR(255) NOT NULL UNIQUE,
	Descricao VARCHAR(500) NOT NULL,
	DataDeLancamento DATE NOT NULL,
	Valor DECIMAL NOT NULL,
	IdEstudio INT FOREIGN KEY REFERENCES Estudio (IdEstudio) 
);
GO

CREATE TABLE TipoUsuario(
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(255) NOT NULL
);
GO

CREATE TABLE Usuarios(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Email VARCHAR(255) NOT NULL UNIQUE,
	Senha VARCHAR(255) NOT NULL,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario( IdTipoUsuario)
);
GO

